1. Импортируйте пакет numpy под именем np

In [2]:
import numpy as np

2. Распечатайте версию numpy

In [3]:
print(np.__version__)

2.1.3


3. Создайте вектор со значениями от 10 до 49 

In [4]:
print(np.arange(10, 50))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Перевернуть вектор (первый элемент становится последним)

In [5]:
print(np.flip(np.arange(10, 50)))

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


5. Создайте массив 5x5 со случайными значениями и найдите среднее значение и медиану для каждой строки

In [6]:
A = np.random.random((5,5))
print(A)

[[0.75691818 0.18565017 0.04504572 0.58191782 0.2674345 ]
 [0.27682114 0.84954545 0.66474845 0.47959008 0.37791713]
 [0.27302549 0.22925942 0.17320968 0.95759059 0.96887804]
 [0.90255221 0.45351859 0.89953464 0.2676405  0.09229474]
 [0.6402379  0.05357216 0.97745516 0.43858276 0.65780794]]


[0.36739328 0.52972445 0.52039264 0.52310814 0.55353118]


array([0.77621004, 0.63715337, 0.49428744, 0.81732248, 0.43085952])

In [8]:
print(np.mean(A, axis = 1))

[0.36739328 0.52972445 0.52039264 0.52310814 0.55353118]


In [9]:
print(np.median(A, axis = 1))

[0.2674345  0.47959008 0.27302549 0.45351859 0.6402379 ]


6. Преобразуйте одномерный массив из 27 элементов целого типа в трехмерный (3x3x3)

In [10]:
a = np.array([x for x in range(27)])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [12]:
print(a.reshape(3, 3, 3))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


7. Преобразуйте все элементы массива numpy из типа данных float в integer

In [13]:
a = np.array([[3.5, 1.9, 8.45], [4.7, 7.9, 1.9]])

[[3 1 8]
 [4 7 1]]


In [14]:
a1 = np.astype(a, int)
print(a1)

[[3 1 8]
 [4 7 1]]


8. Преобразуйте двоичный массив numpy [[1, 0, 0], [1, 1, 1],  [0, 0, 1]] (содержащий только 0 и 1) в логический массив numpy

In [15]:
a = np.array([[1, 0, 0], [1, 1, 1],  [0, 0, 1]])

[[ True False False]
 [ True  True  True]
 [False False  True]]


In [16]:
a1 = np.astype(a,bool)
print(a1)

[[ True False False]
 [ True  True  True]
 [False False  True]]


9. Расположите 2 массива numpy горизонтально (hstack), т.е. 2 массива, имеющих одинаковое 1-е измерение (количество строк в 2D-массивах)

In [17]:
a1 = np.array([[1,2,3], [4,5,6]])
a2 = np.array([[7,8,9], [10,11,12]])

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [19]:
a3 = np.hstack((a1,a2))
print(a3)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


10. Расположите 2 массива numpy вертикально (vstack), т.е. 2 массива, имеющие одинаковое последнее измерение (количество столбцов в 2D-массивах)

In [20]:
a1 = np.array([[1,2],
 [3,4],
 [5,6]])

a2 = np.array([[7,8],
 [9,10],
 [10,11]])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [10 11]]


In [21]:
a3 = np.vstack((a1,a2))
print(a3)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [10 11]]


11. Из 2 массивов numpy извлеките индексы, в которых совпадают элементы (np.where)

In [23]:
a = np.array([1,2,3,4,5])
b = np.array([1,3,2,4,5])

(array([0, 3, 4], dtype=int64),)


In [24]:
print(np.where(a==b))

(array([0, 3, 4]),)


12. Выведите результат умножения 2 матриц (в виде массива numpy)

In [25]:
a = np.array([[1,2,3], 
 [4,5,6], 
 [7,8,9]])

b = np.array([[2,3,4], 
 [5,6,7], 
 [8,9,10]])

[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]


[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]


In [27]:
print(np.dot(a,b))

[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]


13. Выведите транспонированную матрицу

In [28]:
a = np.array([[1,2,3], 
 [4,5,6], 
 [7,8,9]])

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [29]:
print(np.matrix_transpose(a))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

14. Вычислите синус массива углов (в радианах) с помощью NumPy

In [31]:
angles = np.array([3.14, 3.14/2, 6.28])

[ 0.00159265  0.99999968 -0.0031853 ]


In [32]:
print(np.sin(angles))

[ 0.00159265  0.99999968 -0.0031853 ]


15. Отсортировать вектор

In [33]:
v = np.random.random(size=[10])
print(v)

[0.29456447 0.05599738 0.87176797 0.91017728 0.54177261 0.19016595
 0.38898042 0.09667289 0.2940381  0.78567483]


[0.13178341 0.14962622 0.26204075 0.30821184 0.34446024 0.45199466
 0.51581108 0.79408365 0.87313982 0.88810901]


In [34]:
print(np.sort(v))

[0.05599738 0.09667289 0.19016595 0.2940381  0.29456447 0.38898042
 0.54177261 0.78567483 0.87176797 0.91017728]


16. Проверить, одинаковы ли два NumPy массива

In [36]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])

True


In [37]:
print(np.allclose(a, b))

True


17. В одномерном массиве заменить максимальный элемент на ноль

In [40]:
Z = np.random.random(10)

In [74]:
Z

array([0.16782157, 0.13655578, 0.59454878, 0.02957322, 0.81242629,
       0.71645444, 0.48757387, 0.05812814, 0.21499663, 0.24011352])

[0.16782157 0.13655578 0.59454878 0.02957322 0.         0.71645444
 0.48757387 0.05812814 0.21499663 0.24011352]


In [41]:
print(Z)

[0.59947682 0.87094366 0.44017158 0.97146903 0.38448261 0.22418354
 0.66531845 0.87717679 0.55259618 0.50285714]


In [42]:
print(np.where(Z == np.max(Z), 0, Z))

[0.59947682 0.87094366 0.44017158 0.         0.38448261 0.22418354
 0.66531845 0.87717679 0.55259618 0.50285714]


18. Замените все нечетные числа одномерного массива на -1.

In [43]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
print(arr)
arr = np.where(arr % 2 != 0, -1, arr)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [80]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. Замените все элементы в массиве NumPy больше 30 или меньше 5 новым значением 10 

In [45]:
arr = np.array([0, 1, 20, 3, 4, 5, 6, -7, 8, 90])

In [46]:
print(arr)
arr = np.where(arr > 30, 10, arr)
arr = np.where(arr < 5, 10, arr)
print(arr)

[ 0  1 20  3  4  5  6 -7  8 90]
[10 10 20 10 10  5  6 10  8 10]


In [90]:
arr

array([10, 10, 20, 10, 10,  5,  6, 10,  8, 10])

20. Отсортируйте двумерный массив по столбцам

In [47]:
a = np.array([[11,5,3], 
 [4,15,6], 
 [7,8,19]])

array([[ 4,  5,  3],
       [ 7,  8,  6],
       [11, 15, 19]])

In [48]:
print(np.sort(a,axis=0))

[[ 4  5  3]
 [ 7  8  6]
 [11 15 19]]
